words = [
    "actionlint",
    "bashls",
    "cbfmt",
    "codelldb",
    "commitlint",
    "cpptools",
    "doctoc",
    "dotenv",
    "editorconfig",
    "fixjson",
    "gitleaks",
    "gitlint",
    "gitui",
    "groovyls",
    "hypr",
    "hyprls",
    "isort",
    "jdtls",
    "jqls",
    "justfile",
    "lemminx",
    "mdslw",
    "oxlint",
    "pgformatter",
    "prettierd",
    "rpmlint",
    "rpmspec",
    "rustywind",
    "semgrep",
    "shellcheck",
    "shellharden",
    "shfmt",
    "snyk",
    "stylelint",
    "taplo",
    "tombi",
    "tsgo",
    "yamlls",
]
